= dzslides backend for AsciiDoc Python
Dan Allen

An AsciiDoc backend that renders the AsciiDoc source as a dzslides presentation.
dzslides is modern presentation framework based on HTML5 and CSS3.

WARNING: The dzslides backend for AsciiDoc Python is no longer under active development.
It has been superceded by the dzslides backend for Asciidoctor, available in the https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/dzslides/README.adoc[Asciidoctor backends] repository.

This backend is designed to work specifically with a fork of the dzslides project at https://github.com/mojavelinux/dzslides.

== Installation

To install the dzslides backend, install it into asciidoc backends through git
(you'll need AsciiDoc version 8.6.6 or newer):

----
mkdir -p ~/.asciidoc/backends/
cd ~/.asciidoc/backends/
git clone https://github.com/mojavelinux/asciidoc-dzslides-backend.git dzslides
----

Next, descend into the dzslides backend and clone dzslides itself (from the mojavelinux/dzsldies repo):

----
cd dzslides
git clone https://github.com/mojavelinux/dzslides.git
----

IMPORTANT: If you enable the `linkcss` attribute, you'll also need to checkout dzslides in the same directory as the presentation.

== Usage

Use the 'dzslides' backend as you would the built-in backends.

== Example

As you would expect, the rendered output looks just like any other dzslides presentation.

Refer to http://mojavelinux.github.com/decks[these presentations] to see examples of the rendered output and the AsciiDoc source that produced them using this backend.
